# Utiliser l'image officielle de PHP avec Apache
FROM php:apache

# Copier le fichier index.php dans le répertoire du serveur web
COPY index.php /var/www/html/

# Exposer le port 80 du conteneur
EXPOSE 80
